import{a as w,S as v,i as l}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const S="47057239-824e754b75c5fca36ae14ba66",E="https://pixabay.com/api/";async function u(r,o=1){const n={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await w.get(E,{params:n})).data}catch(e){throw console.error("Error fetching images:",e),e}}function f(r){const o=document.querySelector(".gallery"),i=r.map(({webformatURL:n,largeImageURL:e,tags:t,likes:s=0,views:p=0,comments:b=0,downloads:L=0})=>`
        <div class="photo-card">
          <a href="${e}" target="_blank" rel="noopener noreferrer">
            <img src="${n}" alt="${t}" loading="lazy" />
          </a>
         <div class="info">
          <p class="info-item"><b>Likes:</b> ${s}</p>
          <p class="info-item"><b>Views:</b> ${p}</p>
          <p class="info-item"><b>Comments:</b> ${b}</p>
          <p class="info-item"><b>Downloads:</b> ${L}</p>
        </div>
      </div>
      `).join("");o.insertAdjacentHTML("beforeend",i)}function P(){const r=document.querySelector(".gallery");r.innerHTML=""}let m=new v(".gallery a");const q=document.querySelector("#search-form"),d=document.querySelector(".load-more"),h=document.getElementById("loader");let a=1,c="";q.addEventListener("submit",$);d.addEventListener("click",I);function g(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}async function $(r){if(r.preventDefault(),P(),c=r.currentTarget.elements.query.value.trim(),!!c){a=1,g();try{const o=await u(c,a);if(o.hits.length===0){l.info({title:"Info",message:"No images found. Please try a different query."}),d.classList.add("hidden");return}f(o.hits),m.refresh(),d.classList.remove("hidden")}catch(o){l.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(o)}finally{y()}}}async function I(){a+=1,g();try{const r=await u(c,a);f(r.hits),m.refresh(),O(),(r.hits.length<15||r.totalHits<=a*15)&&(d.classList.add("hidden"),l.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(r){l.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(r)}finally{y()}}function O(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
