import{a as v,S as E,i as f}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const P="47057239-824e754b75c5fca36ae14ba66",q="https://pixabay.com/api/";async function g(t,r=1){const s={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await v.get(q,{params:s})).data}catch(e){throw console.error("Error fetching images:",e),e}}function m(t){const r=document.querySelector(".gallery"),l=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:a=0,views:b=0,comments:w=0,downloads:S=0})=>`
        <div class="photo-card">
          <a href="${e}" target="_blank" rel="noopener noreferrer">
            <img src="${s}" alt="${o}" loading="lazy" />
          </a>
         <div class="info">
          <p class="info-item"><b>Likes:</b> ${a}</p>
          <p class="info-item"><b>Views:</b> ${b}</p>
          <p class="info-item"><b>Comments:</b> ${w}</p>
          <p class="info-item"><b>Downloads:</b> ${S}</p>
        </div>
      </div>
      `).join("");r.insertAdjacentHTML("beforeend",l)}function M(){const t=document.querySelector(".gallery");t.innerHTML=""}let h=new E(".gallery a");const $=document.querySelector("#search-form"),u=document.querySelector(".gallery"),i=document.querySelector(".load-more"),y=document.getElementById("loader");let n;function B(){n||(n=document.createElement("p"),n.className="loading-message",n.textContent="Loading images, please wait...",u.parentNode.insertBefore(n,u))}function I(){B(),n.style.display="block"}function N(){n&&(n.style.display="none")}let c=1,d="";$.addEventListener("submit",O);i.addEventListener("click",x);function p(){y.classList.remove("hidden"),I()}function L(){y.classList.add("hidden"),N()}async function O(t){if(t.preventDefault(),M(),d=t.currentTarget.elements.query.value.trim(),!!d){c=1,p();try{const r=await g(d,c);if(r.hits.length===0){f.info({title:"Info",message:"No images found. Please try a different query."}),i.classList.add("hidden");return}m(r.hits),h.refresh(),r.hits.length<15?i.classList.add("hidden"):i.classList.remove("hidden")}catch(r){f.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(r)}finally{L()}}}async function x(){c+=1,p();try{const t=await g(d,c);m(t.hits),h.refresh(),C(),(t.hits.length<15||t.totalHits<=c*15)&&(i.classList.add("hidden"),f.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(t){f.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(t)}finally{L()}}function C(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
